import models ,schemas 
from sqlalchemy.orm import Session 


def create_category(db: Session, category: schemas.CategoryCreate): #we pass the object here and uh session to interact with database (in database.py)
    db_category = models.Category(category_name=category.category_name) #this creates a category object
    db.add(db_category) #adds it to the database session
    db.commit() # commits it ; basically it is confirming and saving it in the db
    db.refresh(db_category) #this gives category_id generated by db
    return db_category #returns object with id and name 

def get_categories(db: Session): #equivalent to select * from categories 
    return db.query(models.Category).all() #displays all categories 


def create_plant(db: Session , plant : schemas.PlantCreate) : 
  #  db_plant = models.Plant(plant_name = plant.plant_name , price = plant.price ) 
    db_plant = models.Plant(**plant.model_dump())
    db.add(db_plant)
    db.commit()
    db.refresh(db_plant)
    return db_plant

def get_plants(db: Session) :
    return db.query(models.Plant).all()

def create_care_requirements(db: Session , care : schemas.CareRequirementsCreate) :
    db_care = models.Care_Requirements(**care.model_dump())
    db.add(db_care)
    db.commit()
    db.refresh(db_care)
    return db_care

def get_care_requirements(db: Session) :
    return db.query(models.Care_Requirements).all()

def create_sales(db: Session , sales : schemas.SalesCreate) :
    db_sales = models.Sales(**sales.model_dump())
    db.add(db_sales)
    db.commit()
    db.refresh(db_sales)
    return db_sales

def get_sales(db: Session) :
    return db.query(models.Sales).all()

def create_purchases(db: Session , purchase : schemas.PurchasesCreate) :
    db_purchase = models.Purchases(**purchase.model_dump())
    db.add(db_purchase)
    db.commit()
    db.refresh(db_purchase)
    return db_purchase

def get_purchases(db: Session) :
    return db.query(models.Purchases).all()

def create_supplier(db: Session , supplier : schemas.SupplierCreate)   :
    db_supplier = models.Supplier(**supplier.model_dump())
    db.add(db_supplier)
    db.commit()
    db.refresh(db_supplier)
    return db_supplier

def get_suppliers(db: Session) : 
    return db.query(models.Supplier).all() 

def create_customer(db: Session , customer : schemas.CustomerCreate) : 
    db_customer = models.Customer(**customer.model_dump()) 
    db.add(db_customer)
    db.commit()
    db.refresh(db_customer)
    return db_customer

def get_customers(db: Session) :
    return db.query(models.Customer).all()
